### ISSUE TITLE
Host Rego Scripts are not working on pods   

### ISSUE THREAD

**Issue by rshmiel** [aquasecurity/appshield#31]
All the following scripts are configured to work on deployments and not on pods.

1. Host PID 
2. Host IPC
3. Host Aliases
4. Host Network

@ttousai @jerbia FYI

**Comment by jerbia** [comment]
@ttousai can you check if these checks should also apply on the pod level and not just the deployment level?
I mean, a user can run a pod without a deployment.

**Comment by ttousai** [comment]
@jerbia at the moment, these checks won't run for pods as @rshmiel observed. None of the checks will.  I wrote the checks to run only for workloads with a controller.

We can change that to support pods.

**Comment by rshmiel** [comment]
@ttousai please fix just the 4 above. thanks

**Comment by guyyakir** [comment]
@ttousai all the checks are working for pods, except for the 4 scripts mentioned

**Comment by rshmiel** [comment]
@ttousai any updates?

**Comment by rshmiel** [comment]
@jerbia Closing the ticket as @guyyakir fixed the scripts.
We will upload the official files soon....

**Comment by ttousai** [comment]
@guyyakir thanks for  the fix.
