### ISSUE TITLE
Organize the directory structure

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/appshield#45]
The directory structure should be:

/
/kubernetes
/docker
readme.md

**Kubernetes Sub Directory:**
/kubernetes/readme.md
/kubernetes/policies
/kubernetes/policies/pss
/kubernetes/policies/general
/kubernetes/lib
/kubernetes/test

Readme will explain how to run the policy checks and what are the PSS vs. General policies.

**Docker Sub Directory:**
/docker/readme.md
/docker/policies
/docker/lib
/docker/test

**Comment by amitbis** [comment]
All changes are done
